apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: face-operation-scc-role
rules:
- apiGroups:
  - security.openshift.io
  resourcesNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: face-recognition-scc-rolebinding
  namespace: face-recognition
subjects:
- kind: ServiceAccount
  name: face-recognition
  namespace: face-recognition
roleRef:
  kind: ClusterRole 
  name: face-operation-scc-role
  apiGroup: rbac.authorization.k8s.io
