---
apiVersion: v1
kind: Namespace
metadata:
  name: face-recognition
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: face-operation
  namespace: face-recognition
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: face-recognition
   namespace: face-recognition
subjects:
 - kind: ServiceAccount
   name: face-recognition
   namespace: face-recognition
roleRef:
   kind: Role 
   name: face-operation 
   apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: face-recognition
 namespace: face-recognition
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: face-recognition
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: quay.io/rhte_2019/face-recognition:latest
        env:
        - name: VIDEO_INDEX
          value: 0
        volumeMounts:
        - name: devfs
          mountPath: /dev
        - name: devpts
          mountPath: /dev/pts
      volumes:
      - name: devfs
        hostPath:
          path: /dev
      - name: devpts
        hostPath:
          path: /dev/pts

#/dev/:/dev:rslave --mount type=devpts,destination=/dev/pts
