---
apiVersion: v1
kind: Namespace
metadata:
  name: face-recognition
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: face-operation
  namespace: face-recognition
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: face-recognition
   namespace: face-recognition
subjects:
 - kind: ServiceAccount
   name: face-recognition
   namespace: face-recognition
roleRef:
   kind: Role 
   name: face-operation 
   apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: face-recognition
 namespace: face-recognition
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-recognition
  namespace: face-recognition
  labels:
    app: face-recognition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: face-recognition
  template:
    metadata:
      labels:
        app: face-recognition
    spec:
      containers:
      - name: face-recognition
        image: quay.io/rhte_2019/face-recognition:v1
        env:
        - name: VIDEO_INDEX
          value: '0' # /dev/video0
        volumeMounts:
        - name: dev-video0
          mountPath: /dev/video0
        securityContext:
          privileged: true
      volumes:
      - name: dev-video0
        hostPath:
          path: /dev/video0          
